doctrine_mongodb:
    auto_generate_proxy_classes: true
    auto_generate_hydrator_classes: true
    connections:
        default:
            server: '%env(resolve:MONGODB_URL)%'
            options: {}
    default_database: '%env(resolve:MONGODB_DB)%'
    document_managers:
        default:
            auto_mapping: false
            mappings:
                # Foods
                foods:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/mapping/odm/foods/domain'
                    prefix: 'App\Food\Domain'
                foods.projection:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/mapping/odm/foods/projection'
                    prefix: 'App\Food\Infrastructure'
                # Users
                users.domain:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/mapping/odm/users/domain'
                    prefix: 'App\User\Domain'
                users.projection:
                    is_bundle: false
                    type: xml
                    dir: '%kernel.project_dir%/config/mapping/odm/users/projection'
                    prefix: 'App\User\Infrastructure'